server:
  port: 8080

data:
  vaccines:
    pfizer:
      multipliers:
        1: 0.76
        2: 0.17
    moderna:
      multipliers:
        1: 0.76
        2: 0.17
    astrazeneca:
      multipliers:
        1: 0.76
        2: 0.47
    johnson:
      multipliers:
        1: 0.36
    sputnik:
      multipliers:
        1: 0.76
        2: 0.17
    unknown:
      multipliers:
        1: 0.76
        2: 0.47

csv:
  covidcountypopulation: classpath:/data/covid_county_population_usafacts.csv

spring:
  h2:
    console:
      enabled: true
      path: /h2-console/
  datasource:
    url: jdbc:h2:mem:testdb