server:
  port: 8080

data:
  csv:
    covidCountyPopulation: classpath:/data/covid_county_population_usafacts.csv
    covidConfirmed: classpath:/data/covid_confirmed_usafacts.csv
  vaccines:
    pfizer:
      multipliers:
        1: 0.76
        2: 0.17
    moderna:
      multipliers:
        1: 0.76
        2: 0.17
    astrazeneca:
      multipliers:
        1: 0.76
        2: 0.47
    johnson:
      multipliers:
        1: 0.36
    sputnik:
      multipliers:
        1: 0.76
        2: 0.17
    unknown:
      multipliers:
        1: 0.76
        2: 0.47

spring:
  h2:
    console:
      enabled: true
      path: /h2-console/
  datasource:
    url: jdbc:h2:mem:testdb

# Exaposes actuation endpoints
management:
  security:
    enabled: false
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true
#    probes:
#      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: readinessProbe
          show-details: always

info:
  artifact: "@project.artifactId@"
  name: "@project.name@"
  description: "@project.description@"
  version: "@project.version@"